### ISSUE TITLE
error trying to create the organization

### ISSUE THREAD

**Issue by guillelos** [ksator/junos-automation-with-AWX#2]
everything works fine until I try to run the configure script. :(

root@localhost junos-automation-with-AWX]# python configure_awx.py
failed to create the organization Juniper
Traceback (most recent call last):
  File "configure_awx.py", line 259, in <module>
    organization_id = get_the_id_of_the_organization()
  File "configure_awx.py", line 49, in get_the_id_of_the_organization
    for item in rest_call.json()['results']:
KeyError: 'results'

**Comment by guillelos** [comment]
Hi Ksator ,
               quick question , this script run throught the API , but I don't see do you setup the user and password to use with the AWX Api?

Thanks a lot
Kindly Regards,
Guillermo

**Comment by guillelos** [comment]
Nevermind , Found it ;) Thanks it works

**Comment by ksator** [comment]
Hello @guillelos   
OK thanks for the update. 
Cheers
Khelil
